### ISSUE TITLE
Significant memory usage regression with #59 on large grammars

### ISSUE THREAD

**Issue by krame505** [schwerdf/copper#60]
To test out the new features in #59 I tried commenting out the associativity and precedence for `Or_t` in the Silver compiler:
```
terminal Or_t          '||' lexer classes {OP};--, precedence = 5, association = left;
```
`./self-compile` now just hangs at parser generation with high memory usage, and does not print anything, even if I bump it up the heap size by 10 GB.  It eventually crashes with a "java heap space" error.  

This behavior only happens when there is a parser conflict; Copper functions normally with an unambiguous grammar.

**Comment by krame505** [comment]
@keltono Do you think you will be able to get to this in the next day or two?  If not we should probably roll this back in the meantime.

**Comment by keltono** [comment]
Just saw this now --- I probably won't have time tonight or Friday, but I will be able to try to solve it this weekend. We can revert it in the meantime if that would be best.

**Comment by krame505** [comment]
That's probably fine - in the meantime, as workaround for Silver users, one can run `./fetch-jars master --copper` to pull the Copper jars from the last Silver release.

**Comment by keltono** [comment]
Looks like I fixed it --- I don't get significant slowdowns on injecting shift-reduce errors into silver anymore. 
Do you have any more challenging test cases I can try to stress test the counterexample search?  Would be best to see how it performs for more complex examples.
I'll open the PR now since it fixes the problem for the grammars I've tested.

**Comment by mingodad** [comment]
I do have a collection of LARL(1) grammars here https://mingodad.github.io/parsertl-playground/playground/ that could be converted to copper format for test it.
